interface StatCardProps {
  number: string
  numberColor: string
  label: string
}

function StatCard({ number, numberColor, label }: StatCardProps) {
  return (
    <div className="group relative flex h-[200px] w-[300px] shrink-0 flex-col justify-between overflow-hidden rounded-[8px] border border-white/10 bg-[#19161c] p-6 shadow-[0_20px_40px_rgba(0,0,0,0.4)] transition-all duration-300 hover:border-white/20">
      <div
        className="pointer-events-none absolute -right-10 -bottom-10 h-32 w-32 rounded-full opacity-10 blur-xl transition-opacity duration-300 group-hover:opacity-20"
        style={{ backgroundColor: numberColor }}
        aria-hidden="true"
      />
      <span
        className="font-[family-name:var(--font-darker)] text-[42px] font-semibold leading-none tracking-wide"
        style={{ color: numberColor }}
      >
        {number}
      </span>
      <p className="font-[family-name:var(--font-work)] text-[12px] font-normal leading-[1.3] text-[#bababa]">
        {label}
      </p>
    </div>
  )
}

interface StoryCardProps {
  width?: 'w-[300px]' | 'w-[600px]'
  height?: 'h-[200px]' | 'h-[420px]'
  title?: string
  description: string
  accentColor?: string
  imageUrl?: string
}

function StoryCard({
  width = 'w-[300px]',
  height = 'h-[200px]',
  title,
  description,
  accentColor = '#6843ec',
  imageUrl,
}: StoryCardProps) {
  return (
    <div
      className={`group relative flex ${width} ${height} shrink-0 flex-col justify-end overflow-hidden rounded-[8px] border border-white/10 bg-[#16131a] p-6 shadow-[0_20px_40px_rgba(0,0,0,0.5)] transition-all duration-300 hover:border-white/25`}
    >
      {/* Background Image */}
      {imageUrl && (
        <img
          src={imageUrl}
          alt={title || ''}
          className="pointer-events-none absolute inset-0 h-full w-full object-cover select-none transition-transform duration-700 ease-out group-hover:scale-105"
        />
      )}

      {/* Subtle abstract background lighting */}
      <div
        className="pointer-events-none absolute -right-12 -top-12 h-44 w-44 rounded-full opacity-30 blur-2xl transition-opacity duration-300 group-hover:opacity-45"
        style={{ backgroundColor: accentColor }}
        aria-hidden="true"
      />

      {/* Dark gradient overlay for high contrast readability */}
      <div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-[#0b0a0e] via-[#0b0a0e]/60 to-[#0b0a0e]/20" />

      {/* Content */}
      <div className="relative z-10 flex flex-col gap-1.5">
        {title && (
          <h4 className="font-sans text-[20px] font-semibold leading-snug text-white drop-shadow-[0_2px_4px_rgba(0,0,0,0.8)]">
            {title}
          </h4>
        )}
        <p className="font-sans text-[14px] font-normal leading-relaxed text-[#d1d1d1] drop-shadow-[0_1px_2px_rgba(0,0,0,0.8)]">
          {description}
        </p>
      </div>
    </div>
  )
}

function GalleryTrack({ 'aria-hidden': ariaHidden }: { 'aria-hidden'?: 'true' | 'false' }) {
  return (
    <div
      className="flex shrink-0 items-start gap-5 pr-5"
      aria-hidden={ariaHidden}
    >
      {/* Column 1: Stacked 300x200 */}
      <div className="flex flex-col gap-5">
        <StatCard
          number="48,000"
          numberColor="#6843ec"
          label="Images generated by artificial intelligence"
        />
        <StoryCard
          title="Solana Mobile Announcement"
          description="Users, developers, and reporters were on the scene when Solana Labs announced the Solana Mobile Stack and Saga device in June 2022."
          accentColor="#8b5cf6"
          imageUrl="https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80"
        />
      </div>

      {/* Column 2: Featured 600x420 */}
      <StoryCard
        width="w-[600px]"
        height="h-[420px]"
        title="Lisbon Breakpoint Conference"
        description="3,800 builders. 3 days. 1 community. Teams from around the world gathered in Lisbon in Nov. 2022 to learn, build, and celebrate at the annual conference from the Solana Foundation."
        accentColor="#06b6d4"
        imageUrl="https://images.unsplash.com/photo-1511578314322-379afb476865?w=1200&auto=format&fit=crop&q=80"
      />

      {/* Column 3: Stacked 300x200 */}
      <div className="flex flex-col gap-5">
        <StoryCard
          title="New York Hacker House"
          description="Start spreading the news. Lines were out the door at the Solana Foundation’s New York Hacker House in March 2022."
          accentColor="#3b82f6"
          imageUrl="https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=600&auto=format&fit=crop&q=80"
        />
        <StatCard
          number="48,000"
          numberColor="#d2ff3a"
          label="Images generated by artificial intelligence"
        />
      </div>

      {/* Column 4: Portrait 300x420 */}
      <StoryCard
        width="w-[300px]"
        height="h-[420px]"
        title="Seoul Hacker House"
        description="Let’s build! Local devs came to the Solana Foundation’s Seoul Hacker House ahead of Korea Blockchain Week 2022."
        accentColor="#ec4899"
        imageUrl="https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80"
      />

      {/* Column 5: Stacked 300x200 */}
      <div className="flex flex-col gap-5">
        <StatCard
          number="3,800"
          numberColor="#ffeb3b"
          label="Solana Breakpoint 2022 attendees"
        />
        <StoryCard
          title="London Hacker House"
          description="Builders joined London Hacker House, a five-day offline event in June 2022, with advice and support from core Solana Lab engineers."
          accentColor="#10b981"
          imageUrl="https://images.unsplash.com/photo-1531482615713-2afd69097998?w=600&auto=format&fit=crop&q=80"
        />
      </div>

      {/* Column 6: Featured 600x420 */}
      <StoryCard
        width="w-[600px]"
        height="h-[420px]"
        title="Seoul Hacker House"
        description="Let’s build! Local devs came to the Solana Foundation’s Seoul Hacker House ahead of Korea Blockchain Week 2022."
        accentColor="#a855f7"
        imageUrl="https://images.unsplash.com/photo-1538485399081-7191377e8241?w=1200&auto=format&fit=crop&q=80"
      />

      {/* Column 7: Stacked 300x200 */}
      <div className="flex flex-col gap-5">
        <StoryCard
          title="New Delhi Hacker House"
          description="Vibe. Mint. Build. Thousands of developers came to build together at the Sept. 2022 New Delhi Solana Hacker House."
          accentColor="#f59e0b"
          imageUrl="https://images.unsplash.com/photo-1528605248644-14dd04022da1?w=600&auto=format&fit=crop&q=80"
        />
        <StatCard
          number="1,075"
          numberColor="#00bcd4"
          label="Daily programs used"
        />
      </div>

      {/* Column 8: Portrait 300x420 */}
      <StoryCard
        width="w-[300px]"
        height="h-[420px]"
        title="Solana Miami"
        description="New and native users came to Solana Miami in April 2022 to build, learn, and see real world Solana use cases."
        accentColor="#06b6d4"
        imageUrl="https://images.unsplash.com/photo-1506953823976-52e1fdc0149a?w=800&auto=format&fit=crop&q=80"
      />
    </div>
  )
}

export function SectionImage() {
  return (
    <section
      id="gallery"
      aria-label="Journey Through Art of community"
      className="relative z-10 -mx-6 mt-32 mb-28 overflow-hidden sm:-mx-10 lg:-mx-[99px]"
    >
      {/* Section Title */}
      <div className="mx-auto mb-12 max-w-[1440px] px-6 text-center sm:px-10 lg:px-[99px]">
        <h2 className="font-[family-name:var(--font-darker)] text-[40px] font-semibold leading-tight tracking-[1px] text-white sm:text-[46px]">
          Journey Through Art of community
        </h2>
      </div>

      {/* Horizontal Infinite Marquee */}
      <div className="relative w-full overflow-hidden">
        {/* Left & Right Edge Fade Gradients */}
        <div className="pointer-events-none absolute inset-y-0 left-0 z-20 w-16 bg-gradient-to-r from-black to-transparent sm:w-32" />
        <div className="pointer-events-none absolute inset-y-0 right-0 z-20 w-16 bg-gradient-to-l from-black to-transparent sm:w-32" />

        {/* Seamless Looping Track */}
        <div className="animate-marquee py-4">
          <GalleryTrack />
          <GalleryTrack aria-hidden="true" />
        </div>
      </div>
    </section>
  )
}
