interface StatCardProps {
  number: string
  numberColor: string
  label: string
}

function StatCard({ number, numberColor, label }: StatCardProps) {
  return (
    <div className="relative flex h-[200px] w-[300px] shrink-0 flex-col justify-between rounded-[8px] border border-white/5 bg-[#19161c] p-6 shadow-[0_20px_40px_rgba(0,0,0,0.4)]">
      <span
        className="font-[family-name:var(--font-darker)] text-[42px] font-semibold leading-none tracking-wide"
        style={{ color: numberColor }}
      >
        {number}
      </span>
      <p className="font-[family-name:var(--font-work)] text-[12px] font-normal leading-[1.3] text-[#bababa]">
        {label}
      </p>
    </div>
  )
}

interface StoryCardProps {
  width?: 'w-[300px]' | 'w-[600px]'
  height?: 'h-[200px]' | 'h-[420px]'
  title?: string
  description: string
  accentColor?: string
}

function StoryCard({
  width = 'w-[300px]',
  height = 'h-[200px]',
  title,
  description,
  accentColor = '#6843ec',
}: StoryCardProps) {
  return (
    <div
      className={`relative flex ${width} ${height} shrink-0 flex-col justify-end overflow-hidden rounded-[8px] border border-white/5 bg-[#19161c] p-6 shadow-[0_20px_40px_rgba(0,0,0,0.4)]`}
    >
      {/* Subtle abstract background lighting */}
      <div
        className="pointer-events-none absolute -right-12 -top-12 h-44 w-44 rounded-full opacity-15 blur-2xl"
        style={{ backgroundColor: accentColor }}
        aria-hidden="true"
      />
      <div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-black/85 via-black/40 to-transparent" />

      {/* Content */}
      <div className="relative z-10 flex flex-col gap-1.5">
        {title && (
          <h4 className="font-sans text-[20px] font-normal leading-snug text-white">
            {title}
          </h4>
        )}
        <p className="font-sans text-[15px] font-normal leading-relaxed text-[#c4c4c4]">
          {description}
        </p>
      </div>
    </div>
  )
}

export function SectionImage() {
  return (
    <section
      id="gallery"
      aria-label="Journey Through Art of community"
      className="relative z-10 -mx-6 mt-32 mb-40 overflow-hidden sm:-mx-10 lg:-mx-[99px]"
    >
      {/* Section Title */}
      <div className="mx-auto mb-12 max-w-[1440px] px-6 text-center sm:px-10 lg:px-[99px]">
        <h2 className="font-[family-name:var(--font-darker)] text-[40px] sm:text-[46px] font-semibold leading-tight tracking-[1px] text-white">
          Journey Through Art of community
        </h2>
      </div>

      {/* Horizontal Mosaic Scroll Track */}
      <div className="relative w-full">
        {/* Left & Right Edge Fade Gradients */}
        <div className="pointer-events-none absolute inset-y-0 left-0 z-20 w-16 bg-gradient-to-r from-black to-transparent sm:w-28" />
        <div className="pointer-events-none absolute inset-y-0 right-0 z-20 w-16 bg-gradient-to-l from-black to-transparent sm:w-28" />

        {/* Scrollable Container */}
        <div className="flex w-full overflow-x-auto py-4 pl-6 pr-12 scrollbar-none sm:pl-10 lg:pl-[99px]">
          <div className="flex shrink-0 items-start gap-5">
            {/* Column 1: Stacked 300x200 */}
            <div className="flex flex-col gap-5">
              <StatCard
                number="48,000"
                numberColor="#6843ec"
                label="Images generated by artificial intelligence"
              />
              <StoryCard
                title="Solana Mobile Announcement"
                description="Users, developers, and reporters were on the scene when Solana Labs announced the Solana Mobile Stack and Saga device in June 2022."
                accentColor="#8b5cf6"
              />
            </div>

            {/* Column 2: Featured 600x420 */}
            <StoryCard
              width="w-[600px]"
              height="h-[420px]"
              title="Lisbon Breakpoint Conference"
              description="3,800 builders. 3 days. 1 community. Teams from around the world gathered in Lisbon in Nov. 2022 to learn, build, and celebrate at the annual conference from the Solana Foundation."
              accentColor="#06b6d4"
            />

            {/* Column 3: Stacked 300x200 */}
            <div className="flex flex-col gap-5">
              <StoryCard
                title="New York Hacker House"
                description="Start spreading the news. Lines were out the door at the Solana Foundation’s New York Hacker House in March 2022."
                accentColor="#3b82f6"
              />
              <StatCard
                number="48,000"
                numberColor="#d2ff3a"
                label="Images generated by artificial intelligence"
              />
            </div>

            {/* Column 4: Portrait 300x420 */}
            <StoryCard
              width="w-[300px]"
              height="h-[420px]"
              title="Seoul Hacker House"
              description="Let’s build! Local devs came to the Solana Foundation’s Seoul Hacker House ahead of Korea Blockchain Week 2022."
              accentColor="#ec4899"
            />

            {/* Column 5: Stacked 300x200 */}
            <div className="flex flex-col gap-5">
              <StatCard
                number="3,800"
                numberColor="#ffeb3b"
                label="Solana Breakpoint 2022 attendees"
              />
              <StoryCard
                title="London Hacker House"
                description="Builders joined London Hacker House, a five-day offline event in June 2022, with advice and support from core Solana Lab engineers."
                accentColor="#10b981"
              />
            </div>

            {/* Column 6: Featured 600x420 */}
            <StoryCard
              width="w-[600px]"
              height="h-[420px]"
              title="Seoul Hacker House"
              description="Let’s build! Local devs came to the Solana Foundation’s Seoul Hacker House ahead of Korea Blockchain Week 2022."
              accentColor="#a855f7"
            />

            {/* Column 7: Stacked 300x200 */}
            <div className="flex flex-col gap-5">
              <StoryCard
                title="New Delhi Hacker House"
                description="Vibe. Mint. Build. Thousands of developers came to build together at the Sept. 2022 New Delhi Solana Hacker House."
                accentColor="#f59e0b"
              />
              <StatCard
                number="1,075"
                numberColor="#00bcd4"
                label="Daily programs used"
              />
            </div>

            {/* Column 8: Portrait 300x420 */}
            <StoryCard
              width="w-[300px]"
              height="h-[420px]"
              title="Solana Miami"
              description="New and native users came to Solana Miami in April 2022 to build, learn, and see real world Solana use cases."
              accentColor="#06b6d4"
            />
          </div>
        </div>
      </div>
    </section>
  )
}
